### ISSUE TITLE
[Bug]: Indentation isn't well setup

### ISSUE THREAD

**Issue by bpingris** [nvim-flutter/flutter-tools.nvim#103]
**Describe the bug**
When creating a new line (`<CR>, o, O`), the indentation won't be "smart".
I included a video that shows the issue I'm talking about.

Not sure if it's related to the lsp client or your plugin.

Here's my configuration about tabs:
```lua
opt.tabstop = 4
opt.softtabstop = 4
opt.shiftwidth = 4
opt.smarttab = true
opt.expandtab = true
```

**Expected behavior**
After a declaration of a function (for example), when pressing enter the cursor should be indented inside the body of the function. Here it is aligned with the beginning of the function's name on the line above.

**Video**

https://user-images.githubusercontent.com/29386109/138500757-78c1e3a9-b286-46d0-9085-5670bd998b8c.mov

**System information**

- OS: MacOS Big Sur 11.6
- Flutter version: Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
- Is flutter in $PATH: ye
- neovim version: NVIM v0.5.1

**Comment by cncsl** [comment]
> Yea it was what I expected, but wanted to be sure it was not related to the plugin, thanks for the response.
> 
> Another quick question, I find the dart lsp really slow: it takes time to find autocompletion item, sometimes vim hangs for a solid 1-2 second(s) when modifying the buffer, basically "every" action that requires the lsp takes time, do you have any idea on this?



> **Describe the bug** When creating a new line (`<CR>, o, O`), the indentation won't be "smart". I included a video that shows the issue I'm talking about.
> 
> Not sure if it's related to the lsp client or your plugin.
> 
> Here's my configuration about tabs:
> 
> ```lua
> opt.tabstop = 4
> opt.softtabstop = 4
> opt.shiftwidth = 4
> opt.smarttab = true
> opt.expandtab = true
> ```
> 
> **Expected behavior** After a declaration of a function (for example), when pressing enter the cursor should be indented inside the body of the function. Here it is aligned with the beginning of the function's name on the line above.
> 
> **Video**
> 
>  Screen.Recording.2021-10-22.at.19.46.58.mov 
> **System information**
> 
> * OS: MacOS Big Sur 11.6
> * Flutter version: Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
> * Is flutter in $PATH: ye
> * neovim version: NVIM v0.5.1

hello @bpingris , did you solve the indentation problem later?

**Comment by bpingris** [comment]
@cncsl I can't remember, it's been 3 years I don't do any flutter development now
and all the tools mentioned here have been updated so maybe the issue has been fixed

if you still have it and believe it's related to this plugin I think you should open a new issue

**Comment by cncsl** [comment]
@bpingris thx for reply so fast, you are right, I will try to figure out in other place. have a nice day

**Comment by scholar7r** [comment]
> [@bpingris](https://github.com/bpingris) thx for reply so fast, you are right, I will try to figure out in other place. have a nice day

The most easier way to figure out the indentation problem is installing a plugin `dart-lang/dart-vim-plugin`, flutter-tools.nvim do not handle things like indent, without this, (neo)vi(m) also don't have a solution for 

Maybe you have figured out this problem, but I really want to someone who don't know how to handle it to know this solution.   :)
