### ISSUE TITLE
[Bug]: it has an error about installing flutter-tools.nvim #2813

### ISSUE THREAD

**Issue by hawkinchina** [nvim-flutter/flutter-tools.nvim#164]
packer.nvim: Error running config for flutter-tools.nvim: ...ck/packer/start/flutter-tools.nvim/lua/flutter-tools.lua:75: attempt to call field 'nvim_create_augroup' (a nil value)

**Comment by akinsho** [comment]
@hawkinchina please ensure you are on the latest stable version on neovim. This error sounds like you are running an old version of neovim. This is clarified in the README

**Comment by hawkinchina** [comment]
@akinsho Hi, my neovim: 
NVIM v0.7.0-dev+1136-g005a7aa16 Build type: Release LuaJIT 2.1.0-beta3

**Comment by akinsho** [comment]
This looks like a dev build of neovim 0.7 rather than the stable release of that version, can you please make sure you are on the *stable* release or on neovim 0.8 nightly if using nightlies

**Comment by hawkinchina** [comment]
neovim 7.2 , it is ok. 

but there are two dartls in the status line.

lspInfo:

```
Language client log: /Users/jack/.cache/nvim/lsp.log
 Detected filetype:   dart
 
 2 client(s) attached to this buffer: 
 
 Client: dartls (id: 1, pid: 50512, bufnr: [3])
 	filetypes:       dart
 	autostart:       false
 	root directory:  /Users/jack/AndroidStudioProjects/flutter_ex02_namer
 	cmd:             /Users/jack/flutter_development/flutter/bin/dart /Users/jack/flutter_development/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --lsp
 
 Client: dartls (id: 2, pid: 50513, bufnr: [3])
 	filetypes:       dart
 	autostart:       true
 	root directory:  /Users/jack/AndroidStudioProjects/flutter_ex02_namer
 	cmd:             dart /Users/jack/flutter_development/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --lsp
 
 Configured servers list: angularls, html, dartls

```

**Comment by akinsho** [comment]
@hawkinchina are you on the latest version of this plugin, this should already be fixed from today's PR can you also paste the result of `:lua =vim.lsp.start` and `:lua =vim.version()`

**Comment by hawkinchina** [comment]
:lua =vim.lsp.star
the result :   nil 
---
:lua =vim.version()
the result: 
{
  api_compatible = 0,
  api_level = 9,
  api_prerelease = false,
  major = 0,
  minor = 7,
  patch = 2
}

**Comment by akinsho** [comment]
@hawkinchina this should not be the case on the latest commit of this plugin, are you sure you are not starting a second lsp server using lspconfig or something

**Comment by hawkinchina** [comment]
i will update this plugin.. i will try..thanks.

**Comment by akinsho** [comment]
> are you sure you are not starting a second lsp server using lspconfig or something

☝🏿

Can you also paste the output of `:LspInfo`, and *please provide a minimal neovim configuration* i.e. test without any other plugins just load this plugin and run in a dart file and see if it reproduces with *no other plugins setup*

I will look at this if and when I next get time or if someone else is able to look.

**Comment by hawkinchina** [comment]
I comment  "-- require("lvim.lsp.manager").setup("dartls")".    -> automatically added config.
it will be only one dartls in the status line.

----
lspInfo:

Language client log: /Users/jack/.cache/nvim/lsp.log
 Detected filetype:   dart
 
 2 client(s) attached to this buffer: 
 
 Client: dartls (id: 1, pid: 50512, bufnr: [3])
 	filetypes:       dart
 	autostart:       false
 	root directory:  /Users/jack/AndroidStudioProjects/flutter_ex02_namer
 	cmd:             /Users/jack/flutter_development/flutter/bin/dart /Users/jack/flutter_development/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --lsp
 
 Client: dartls (id: 2, pid: 50513, bufnr: [3])
 	filetypes:       dart
 	autostart:       true
 	root directory:  /Users/jack/AndroidStudioProjects/flutter_ex02_namer
 	cmd:             dart /Users/jack/flutter_development/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --lsp
 
 Configured servers list: angularls, html, dartls

**Comment by hawkinchina** [comment]
thanks.

**Comment by akinsho** [comment]
@hawkinchina please test the setup *without a premade configuration* just use setup directly do not use lunarvim
