### ISSUE TITLE
[BUG] error when running code actions from the outline window

### ISSUE THREAD

**Issue by LikithReddyA** [nvim-flutter/flutter-tools.nvim#244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Throwing follwoing error:
Error executing vim.schedule lua callback: ...re/nvim/lazy/flutter-tools.nvim/lua/flutter-tools/ui.lua:79: attempt to index local 'data' (a nil value)
stack traceback:
	...re/nvim/lazy/flutter-tools.nvim/lua/flutter-tools/ui.lua:79: in function <...re/nvim/lazy/flutter-tools.nvim/lua/flutter-tools/ui.lua:76>
	vim/shared.lua: in function 'tbl_map'
	...re/nvim/lazy/flutter-tools.nvim/lua/flutter-tools/ui.lua:76: in function 'get_telescope_picker_config'
	...re/nvim/lazy/flutter-tools.nvim/lua/flutter-tools/ui.lua:105: in function 'select'
	...lutter-tools.nvim/lua/flutter-tools/lsp/code_actions.lua:53: in function 'create_popup'
	...im/lazy/flutter-tools.nvim/lua/flutter-tools/outline.lua:366: in function 'func'
	...lazy/flutter-tools.nvim/lua/flutter-tools/utils/init.lua:114: in function 'handler'
	/usr/local/share/nvim/runtime/lua/vim/lsp.lua:1399: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>

### Expected Behavior

Code actions in FlutterOutline needs to work

### Steps To Reproduce

 1. Open the flutter project and toggle flutteroutline
 2. Press "a" for code actions

### Environment

```Markdown
- OS: Arch linux
- Flutter version: 3.7.11
- Is flutter in $PATH: yes
- neovim version: 0.9
```

**Comment by akinsho** [comment]
@LikithReddyA tbh I'm thinking of fully deprecating the whole code actions in the outline window functionality. I saw it in vscode or maybe emacs and thought it would be cool to add but it's just led to a bunch of workarounds that constantly cause breakage. In short I think the general recommendation from me for now is to just use code actions in your code as normal not in the outline window. I don't encourage this, it's not a very good way to edit though code as feature I think in hindsight.

I still need to decide if I'm going to entirely deprecate this functionality or what to do with it exactly.

**Comment by sidlatau** [comment]
Code actions functionality was removed in the outline.
