### ISSUE TITLE
save pubspec.yaml , it found the absolute path of flutter

### ISSUE THREAD

**Issue by Decodetalkers** [nvim-flutter/flutter-tools.nvim#275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Emm. this is because I made a tool to auto config my flutter enviroment, link is here https://github.com/Decodetalkers/flutterup

It is like rustup, check the arg[0], and finally run the right target, to provide a package named `flutter` for me to compile package from aur, because these packages mark flutter as their dependenies, and as you know, flutter need a .git folder , it will not run property when in root dir, so I make this one. the flutter, dart, and flutterup target are all `flutterup`, and this causes the problem under.

![image](https://github.com/akinsho/flutter-tools.nvim/assets/60290287/b2b2e17f-05b9-448a-b049-6fa92b315881)

Emm, if it do not need to find the absolute path? I do not know where the code is, and what is this logic for , so I ask here 

### Expected Behavior

I think absolute path maybe not needed ,  I think

### Steps To Reproduce

use the package `flutterup` as flutter.. then it will reproduce

### Environment

```Markdown
- OS:archlinux
- Flutter version: 3.10
- Is flutter in $PATH:Yes, and maybe not the real flutter
- neovim version:0.9.0
```

**Comment by Decodetalkers** [comment]
![image](https://github.com/akinsho/flutter-tools.nvim/assets/60290287/185a76c0-319e-433a-a747-67c78428425c)
the tool is like this, like what rustup do

**Comment by sidlatau** [comment]
Hi,

It seems there hasn’t been any activity on this issue for over a year, and it doesn’t appear to be directly related to this plugin. If there’s still something to address, feel free to comment or open a pull request.

Thanks!

**Comment by Decodetalkers** [comment]
> Hi,
> 
> It seems there hasn’t been any activity on this issue for over a year, and it doesn’t appear to be directly related to this plugin. If there’s still something to address, feel free to comment or open a pull request.
> 
> Thanks!

No, please do not close it. It is the problem of this plugin

I mean there is no need to find the absolute path of flutter and dart. My program uses arg 0 to call the flutter and dart, then it causes this program.

**Comment by Decodetalkers** [comment]
https://github.com/nvim-flutter/flutter-tools.nvim/pull/354  I have made this pr
