### ISSUE TITLE
[BUG] textDocument/formatting not supported on_attach

### ISSUE THREAD

**Issue by preiter93** [nvim-flutter/flutter-tools.nvim#351]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The call to client.supports_method("textDocument/formatting") returns false when called on_attach.

This was not the case a few days ago. Unfortunately, I don't know if it was introduced by the Neovim upgrade to v0.10 or by an upgrade of the Flutter tools (I suspect the former)

Maybe it is related to
https://github.com/akinsho/flutter-tools.nvim/issues/346

### Expected Behavior

The call to client.supports_method("textDocument/formatting") returns true when called on_attach

### Steps To Reproduce

1. Instal nvim 0.10
2. Use this config
```
return {
    'akinsho/flutter-tools.nvim',
    dependencies = { 'mason-lspconfig.nvim', 'nvim-lua/plenary.nvim', 'stevearc/dressing.nvim' },
    opts = {
        lsp = {
            on_attach = function(client, bufnr)
                assert(client.supports_method("textDocument/formatting"), "flutter client must support formatting")
            end,
        }
    }
}
```
3. Notice that it throws an assertion

### Environment

```Markdown
- OS: Macos 14.4.1
- Flutter version: 3.13.3
- Is flutter in $PATH: yes
- neovim version: v0.10
```

**Comment by preiter93** [comment]
> I have noticed something similar too, namely when trying to auto format on save, it isn't formatting. Guessing this is related?

yes, probably, that's how I noticed it too. I think it's common to have code like this
```
-- Autoformatting on save
if client.supports_method(“textDocument/formatting”) then
  vim.api.nvim_create_autocmd(“BufWritePre”, {
    buffer = bufnr,
    callback = function()
      vim.lsp.buf.format({ bufnr = bufnr })
    end,
  })
end
```
which runs in the lsps on_attach. Thats is currently not working. As a workaround I removed the check
```
if client.supports_method(“textDocument/formatting”) then
```
for flutter/dart.

**Comment by CnTeng** [comment]
Close the opened flutter buffer, and reopen it.
Then all the supports_method check will pass, and inlay_hint will show correctly.
It's weird, but works.

**Comment by sidlatau** [comment]
I think this is related to https://github.com/neovim/neovim/pull/23681, now document formatting, code actions, and inlay hints have the property `dynamicRegistration=true`. If I set it to `false` here https://github.com/akinsho/flutter-tools.nvim/blob/990a1349c29f7d474a0cd51355aba773ccc9deea/lua/flutter-tools/lsp/init.lua#L95 or in local config then  `client.supports_method(“textDocument/formatting”)` returns true. But I am not sure what is the correct fix here...

**Comment by sidlatau** [comment]
I investigated this a bit more, here is more information about the problem: https://github.com/neovim/neovim/issues/24229

It is not enough now to check capabilities on `LspAttach`, it may return `false`,  but then the capability may be registered dynamically and the next check will return `true`.
Workarounds for this may be to switch back to static registration:

```lua
flutter_tools.setup {
  lsp = {
    capabilities = {
      textDocument = { formatting = { dynamicRegistration = false } },
    },
}
```
Or do additional check in `client/registerCapability` handler:
```lua
local orig_handler = vim.lsp.handlers["client/registerCapability"]
vim.lsp.handlers["client/registerCapability"] = function(err, result, ctx)
  local orig_result = orig_handler(err, result, ctx)
   -- do something
  return orig_result
end

```
As this is not a plugin bug I will close this issue.
