### ISSUE TITLE
[Help/Feature Request] Select a default device + launch configuration to not select them on every FlutterRun

### ISSUE THREAD

**Issue by ArinFaraj** [nvim-flutter/flutter-tools.nvim#364]
When I run `FlutterDevices` i have to select a device > select a launch configuration > app runs
Or `FlutterRun` > select a launch configuration > app runs [could run it on the unwanted device]

Using something like `FlutterDefault` to select a device and a launch configuration, it should be stored for this session.
Then we could have something like `FlutterRunDefault` that runs the app on the default device/configs.
I hope I get some guidance on how to implement it myself.

**Comment by sidlatau** [comment]
It is already possible to set the default device in the project config: https://github.com/akinsho/flutter-tools.nvim/#project-configuration - have you tried it?

**Comment by ArinFaraj** [comment]
Using exrc is not exactly what i wanted.
here is a comparison for my case of selecting a default configration to launch it everytime i run `FlutterRun`

Using `exrc`:
- getting the device id from flutter devices
- change the default device and configuration in the .nvim.lua file 
- restart neovim
- run the app

Using something like `FlutterDefault`
- run `FlutterDefault` and select default device and launch configuration using a menu
- run the app with `FlutterRunDefault` 

You can automate a lot of things in the exrc but i believe this is a good quality of life feature that makes development faster
This would be very similar to how it's done one vscode by selecting a default launch config + default device and just hitting F5 to run your app.

**Comment by JordanllHarper** [comment]
The `exrc` is for config on a per project basis, but I believe you can set up a global `setup_project({...}` in your config, which you can configure for your use case.

**Comment by sidlatau** [comment]
Closing this, because the plugin already supports setting device per project or globally.
