### ISSUE TITLE
[BUG] Buffer is not 'modifiable'

### ISSUE THREAD

**Issue by maxfornacon** [nvim-flutter/flutter-tools.nvim#366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to run `:FlutterRun` after a while this error appears:
```
Error executing vim.schedule lua callback: ...e/nvim/lazy/flutter-tools.nvim/lua/flutter-tools/log.lua:79: Buffer is not 'mo
difiable'
stack traceback:
        [C]: in function 'nvim_buf_set_lines'
        ...e/nvim/lazy/flutter-tools.nvim/lua/flutter-tools/log.lua:79: in function 'append'
        ...e/nvim/lazy/flutter-tools.nvim/lua/flutter-tools/log.lua:90: in function 'log'
        ...m/lazy/flutter-tools.nvim/lua/flutter-tools/commands.lua:70: in function 'on_run_data'
        ...tter-tools.nvim/lua/flutter-tools/runners/job_runner.lua:33: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Expected Behavior

Run the flutter application

### Steps To Reproduce

1. open project
2. run `:FlutterRun`

### Environment

```Markdown
- OS: macOS
- Flutter version: 3.19
- Is flutter in $PATH: yes
- neovim version: v0.10.0
```

**Comment by justjew** [comment]
I have the same problem

**Comment by rusandorx** [comment]
Having the same issue

**Comment by danimasa** [comment]
+1

**Comment by sidlatau** [comment]
I made some updates to the logic to use the same buffer number when appending lines. You can see the changes here: https://github.com/nvim-flutter/flutter-tools.nvim/commit/9955c98d1587ee92bd452e0c6f39cbd18de5cad9. Please let me know if the issue persists with the updated version of the plugin.

**Comment by elianortega** [comment]
@sidlatau I can confirm that resolve the issue for me locally. Thanks!

**Comment by lala74** [comment]
I still have the same issue with latest [flutter-tools.nvim](https://github.com/nvim-flutter/flutter-tools.nvim)
