### ISSUE TITLE
[BUG] 'flutter run' not compatible with 'open file' ?

### ISSUE THREAD

**Issue by Dieterbe** [nvim-flutter/flutter-tools.nvim#391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i have a project in ~/code/ptc, therefore i run `nvim code/ptc` in my home directory.
when i do FlutterRun, and i get an error, the console output is something like this:
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building:
no rangeStarts found for Articulation.cervicalSpineFlexion
'package:ptc/backend/movements.dart':
Failed assertion: line 72 pos 12: 'rangeStarts.isNotEmpty'

When the exception was thrown, this was the stack:
#2      new ArticulationMovements (package:ptc/backend/movements.dart:72:12)
#3      _ArticulationsScreenState.build.<anonymous closure> (package:ptc/ui/articulations_screen.dart:58:26)

```
normally, i should be able to hover over the filename - e.g. movements.dart - and hit 'gf' to go to the file, however, flutter run puts the 'ptc' part in the path, but vim is already inside the ptc directory, therefore it can't find the path.

the workaround is that a copy paste the output into a different buffer, remove the 'ptc/' and then 'gf' works as expected..

### Expected Behavior

not sure. maybe flutter run shouldn't print the base directory of the project?

### Steps To Reproduce

trigger a bug during execution and try to use 'gf' on the returned file.

### Environment

```Markdown
- OS: arch linux
- Flutter version: 3.22.3
- Is flutter in $PATH: yes
- neovim version: v0.10.1
```

**Comment by sidlatau** [comment]
Thank you for providing detailed information on the issue.

The intention here is to keep the original behaviour because we do not want to modify the logs that we receive from the Flutter framework. The logs are generated directly by Flutter, and altering them could lead to inconsistencies or confusion, especially when debugging across different environments. Maintaining the full path as it is output by Flutter ensures we preserve the integrity of the log information.

**Comment by Dieterbe** [comment]
maybe there's a way to alter 'gf' in lua, to strip the base path

**Comment by sidlatau** [comment]
You could try to use [includeexpr](https://vimhelp.org/options.txt.html#%27includeexpr%27).

**Comment by sidlatau** [comment]
I see this plugin may be doing what you want:
 https://github.com/dart-lang/dart-vim-plugin/blob/4bdc04e2540edf90fda2812434c11d19dc04bc8f/ftplugin/dart.vim#L26

**Comment by sidlatau** [comment]
I am reopening this case, I added package resolve function based on what I found in https://github.com/dart-lang/dart-vim-plugin. @Dieterbe would it be possible for you to test it? If you are using lazy here is example setup to test:
```lua
return {
  "nvim-flutter/flutter-tools.nvim",
  branch = "resolve-url",
....
}
```

**Comment by Dieterbe** [comment]
wow! accommodating the functionality in flutter-tools.nvim's lua code was actually the outcome i was hoping for, but i was not ready to do the work, and i didn't want to impose the burden on you.

i'm excited that you decided to give this a shot, and it will be my pleasure to test it and provide my feedback. stay tuned!
