### ISSUE TITLE
 How to make this more readable?

### ISSUE THREAD

**Issue by niamotullah** [nvim-flutter/flutter-tools.nvim#394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Screenshot from 2024-10-14 18-05-26](https://github.com/user-attachments/assets/b79c7c27-266a-4dc3-9e0c-684128101085)

### Expected Behavior

```dart
(new) ThemeData ThemeData.from(
  something,  < required int >,
    {
       colorScheme,  < required ColorScheme >
       textTheme,    < TextTheme? >
       useMaterial3,  < bool? >
    }
)
```
or something else which is more readable. Which might align parameters somewhere rather than types. or both

### Steps To Reproduce

`shift+k`

### Environment
`neovim`
`lazyvim` with this `flutter-tools.nivm`

_No response_

### Anything else?

I've created a issues on https://github.com/Dart-Code/Dart-Code/issues/5310 and this sounds like this isn't possible on `vscode`.
is it possible to make it more readable on `neovim`?

**Comment by sidlatau** [comment]
This plugin does not change LSP results in any way, to improve readability changes may be done in dart analysis server, as mentioned in Dart-Code issue.
