### ISSUE TITLE
[BUG] out of range error on semantic_tokens.lua when there are unicode characters in code

### ISSUE THREAD

**Issue by gaogao-qwq** [nvim-flutter/flutter-tools.nvim#395]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Similar to https://github.com/neovim/neovim/issues/30675, semantic token highlighting fails when using dartls.
```
Error executing vim.schedule lua callback: ...0.2_1/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:304: ...0.2_1/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:149: index out of range
stack traceback:
	[builtin#36]: at 0x01006b9078
	...0.2_1/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:304: in function 'handler'
	...eovim/0.10.2_1/share/nvim/runtime/lua/vim/lsp/client.lua:687: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```
By adding `offset_encoding = "utf-8"` to opts solved this issue, would be better if it's set by default.

### Expected Behavior

Semantic token highlighting success with no errors.

### Steps To Reproduce

flutter-tools.nvim config
```lua
	opts = {
		debugger = {
			enabled = true,
		},
		widget_guides = {
			enabled = true,
		},
		fvm = true,
		lsp = {
			-- uncomment this line to avoid error
			-- offset_encoding = "utf-8",
			color = {
				enabled = true,
				background = false,
				background_color = { r = 19, g = 17, b = 24 },
				foreground = false,
				virtual_text = true,
				virtual_text_str = "■",
			},
		},
```

### Environment

```Markdown
- OS: macOS 15.0.1 & Arch Linux
- Flutter version: 3.22.2
- Is flutter in $PATH: yes
- neovim version: v0.10.2
```

**Comment by sidlatau** [comment]
Hmm, I am not facing this problem. Are there any additional steps how to reproduce it?
When I add `offset_encoding`, I get this warning:
"warning: multiple different client offset_encodings detected for buffer, this is not supported yet". (Copilot client is attached to the buffer too)

**Comment by gaogao-qwq** [comment]
> Hmm, I am not facing this problem. Are there any additional steps how to reproduce it? When I add `offset_encoding`, I get this warning: "warning: multiple different client offset_encodings detected for buffer, this is not supported yet". (Copilot client is attached to the buffer too)

I haven't found a very stable reproduction step, but what is certain is that all the code that has this problem contains unicode characters e.g. `你好，世界！`

And I think I should close #396 because doing so introduces more problems: dartls throws RangeError when typing unicode characters

**Comment by gaogao-qwq** [comment]
It seems that this problem only appeared after neovim 0.10.2, because after I downgraded neovim to 0.10.1, the problem no longer occurred. And there's already a pr for that problem that's been proposed in neovim, so considering that this is not a problem with this plugin, I think I should close this issue.
