### ISSUE TITLE
[BUG] Unable to restart debugging. Please try ending the debug session and starting again.

### ISSUE THREAD

**Issue by thanhdatvo** [nvim-flutter/flutter-tools.nvim#404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cannot debug flutter with launch.json

### Expected Behavior

Could debug flutter with launch.json

### Steps To Reproduce

My setup for flutter-tools in Lazyvim:
```lua
return {
  "akinsho/flutter-tools.nvim",
  lazy = false,
  dependencies = {
    "nvim-lua/plenary.nvim",
    "stevearc/dressing.nvim", -- optional for vim.ui.select
  },
  config = function()
    require("flutter-tools").setup({
      debugger = {
        enabled = true,
        register_configurations = function(paths)
          local dap = require("dap")
          dap.configurations.dart = {}
          require("dap.ext.vscode").load_launchjs()
        end,
      },
    })
  end,
}
```

This is my launch.json
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "test_delte",
      "program": "${workspaceFolder}/lib/main.dart",
      "request": "launch",
      "type": "dart",
      "flutterMode": "debug"
    }
  ]
}
```

![Screenshot 2024-11-09 at 3 14 08 PM](https://github.com/user-attachments/assets/0f5593ba-1116-4cb7-8fa8-a9c41ebc478f)

I could debug the app with option 1., but could not debug the app with option 2. and 3. (from launch.json)

This is the error in debug console

![Screenshot 2024-11-09 at 3 15 28 PM](https://github.com/user-attachments/assets/489735d5-12ef-467f-b4c9-01b311a7e662)

### Environment

```Markdown
- OS: MacOS
- Flutter version:3.24.1
- Is flutter in $PATH: yes
- neovim version: v0.10.0
```

**Comment by sidlatau** [comment]
I'm using `"program": "lib/main.dart"` without `{workspaceFolder}`. Could you try this in your setup?
Why are there three run options? Is the complete `launch.json` file shared?

**Comment by thanhdatvo** [comment]
@sidlatau Thank you for your suggestion!
I removed `{workspaceFolder}` but the error persists.

Why are there three run options? 
A: I don't know.

Is the complete launch.json file shared?
A: Yes, it is

**Comment by sidlatau** [comment]
Following your provided setup, there should only be a single DAP configuration. However, it looks like more configurations are added somewhere in your config. You may try to remove `register_configurations`, your config does not add any custom flags, `flutter_tools` should be able to run the project with default values.

**Comment by thanhdatvo** [comment]
Hi @sidlatau ,
I removed `register_configurations`, but the repeats still persist, and I could not start debugging (same error appeared).

I double-checked the DAP configuration in the LazyVim setup. I have only two files configured for DAP: one for Golang and one for Flutter. 
I’m not sure if I mistakenly installed any LazyVim plugin that might be affecting how `flutter_tools` works
This is the list of Lazy Vim plugins I installed:

 
![Screenshot 2024-11-14 at 4 29 06 PM](https://github.com/user-attachments/assets/923689d9-31e9-426e-94d9-94cbdf030f62)

**Comment by sidlatau** [comment]
@thanhdatvo I can not debug your local config. Please try to get a *minimal init.lua* with exact reproduction steps.

**Comment by thanhdatvo** [comment]
@sidlatau thank you for reply.
I really appreciate you taking time to help me.
I will try to config nvim with only flutter_tools to see how it works, and will come back to you.

**Comment by thanhdatvo** [comment]
@sidlatau 
Today, I tried to run nvim with Lazyvim [starter](https://www.lazyvim.org/installation)
I only installed flutter_tools and enabled dap.core in LazyExtra
![Screenshot 2024-11-16 at 12 46 21 PM](https://github.com/user-attachments/assets/119c4bdf-acdc-4001-89f6-aff788db985a)
as.l
 
 I kept the same config for flutter_tools. 
 All the mentioned issues still persist.

**Comment by sidlatau** [comment]
I am not familiar with Lazyvim, so maybe it causes an issue. Could you try a minimal setup without Lazyvim? I did not see such problem as you are facing before, so I still assume it is a local config issue.

**Comment by thanhdatvo** [comment]
@sidlatau 
I used to use Packer before switching to LazyVim. However, Packer is now outdated, and I am currently only familiar with LazyVim.

Since you mentioned a minimal init.lua, you likely know how to create one. Could you kindly provide me with a minimal init.lua configuration for Neovim that includes flutter_tools? I’d like to configure and test flutter_tools using this setup.

Thank you very much!

**Comment by sidlatau** [comment]
I suggest to setup everything in a single file, then you could easily share it. I think the easiest way to do it would be with https://github.com/nvim-lua/kickstart.nvim - just remove what you are not using, add flutter-tools and try to reproduce the issue.

**Comment by thanhdatvo** [comment]
@sidlatau 
For some reason, when I switched back to my old LazyVim configuration, it resolved the duplication issue in the VSCode launch configuration (now only showing one test_delete instead of two as before).
![Screenshot 2024-11-18 at 10 01 57 AM](https://github.com/user-attachments/assets/4225a914-fae8-4d04-8205-d848bb507a3d)

However, I tried to run test_delete, the old error still persisted.

**Comment by sidlatau** [comment]
You still haven't provided any minimum reproducible steps.

**Comment by thanhdatvo** [comment]
@sidlatau 
Here is what I experimented:
Here’s what I experimented with:
- 1st Attempt: Configured Neovim with LazyVim, including only flutter-tools (nvim-dap was already installed). Result: The same error occurred when using the VSCode launch option, and the duplication issue persisted.
- 2nd Attempt: Configured Neovim with kickstart, including only flutter-tools (without nvim-dap). Result: No errors, but the VSCode launch option was not available and I only ran, not debugged
- 3rd Attempt: Switched back to my old LazyVim configuration. Result: The error persisted when using the VSCode launch option, but the duplication issue was resolved.

For 2nd Attempt: I failed to config nvim-dap to debug.

I believe I have provided detailed information about all my attempts. To reproduce this issue, you could simply use LazyVim with only flutter-tools installed.

Please let me know if you need any additional information from me.

**Comment by thanhdatvo** [comment]
@sidlatau 
1. I continues to fix problem nvim-dap with kickstart
When I ran :
`lua require("dap").continue() `
I encountered the following error:
`Config references missing adapter `dart`. Available are:`
However, then I started debug session using: 
`FlutterRun`
it worked fine 

2. I think I figured it out.
I reverted back to my config with LazyVim
When I tried to start a debug session using the command:
`lua require("dap").continue() `
I encountered the error: 
` Unable to restart debugging. Please try ending the debug session and starting again.`
However, when I started the session using:
`FlutterRun`
Then it works fine.

I think I’m fine at the moment; however, the description in the README should be updated:
from
`To use the debugger you need to run :lua require('dap').continue()<CR>`
to 
`To use the debugger you need to run :FlutterRun`

I will close this issue for now.
